/**
 * @chikumiku/service-auth - Authentication service Lambda handlers
 */
export {
  handleRegisterParent,
  validateParentRegistration,
  handleVerifyPassword,
  validateVerifyPasswordRequest,
  handleLogout,
  validateLogoutRequest,
  handleListLearners,
  handleEditLearner,
  handleResetLearnerPassword,
  handleDeleteLearner,
  validateEditLearnerRequest,
  handleGetProfile,
  handleUpdateProfile,
  handleChangePassword,
  handleUpdateNotifications,
  handleAddCustomSubject,
  handleDeleteProfile,
  handleGrantConsent,
  handleCheckConsent,
  requireParentalConsent,
  CURRENT_CONSENT_VERSION,
  CONSENT_TEXT,
  executePurge,
  handleCancelDeletion,
  calculateDeletionDate,
  DELETION_WINDOW_DAYS,
  handleRegisterLearner,
  validateLearnerRegistration,
} from './handlers/index';
export type {
  RegisterParentResponse,
  RegisterParentDependencies,
  AuthContext,
  ParentRepository,
  PasswordHasher,
  VerifyPasswordRequest,
  VerifyPasswordSuccessResponse,
  VerifyPasswordDeps,
  LogoutRequest,
  LogoutSuccessResponse,
  LogoutHandlerDeps,
  LearnerRecord,
  EditLearnerRequest,
  ResetLearnerPasswordRequest,
  ManageLearnerRepository,
  ManageLearnerPasswordHasher,
  ManageLearnerDeps,
  ListLearnersResult,
  EditLearnerResult,
  ResetPasswordResult,
  DeleteLearnerResult,
  ParentProfile,
  UpdateProfileRequest,
  ChangePasswordRequest,
  UpdateNotificationsRequest,
  AddCustomSubjectRequest,
  DeleteProfileRequest,
  GetProfileResponse,
  UpdateProfileResponse,
  ChangePasswordResponse,
  UpdateNotificationsResponse,
  AddCustomSubjectResponse,
  DeleteProfileResponse,
  ParentProfileRepository,
  SubjectRepository,
  ProfilePasswordHasher,
  ParentProfileDeps,
} from './handlers/index';
export type { DBClient, ParentRecord } from './clients/db-client';
export type { CognitoClient } from './clients/cognito-client';

export {
  isSensitiveActionAuthorized,
  VERIFICATION_WINDOW_MS,
  validateToken,
  createToken,
  authenticateRequest,
  extractBearerToken,
} from './middleware';
export type {
  DecodedToken,
  TokenValidationResult,
  AuthenticatedUser,
  AuthMiddlewareResult,
  AuthMiddlewareDeps,
} from './middleware';
